ja:
  - id: 1
    typeface: 'ゴシック体'
    key: 'notosans-mono-bold'
    name: 'Noto Sans Mono CJK JP Bold'
    path: 'ja/Noto_Sans_Mono_CJK_JP-Bold.otf'
  - id: 2
    typeface: '極太ゴシック体'
    key: 'mplus-1p-black'
    name: 'M+ 1p black'
    path: 'ja/mplus-1p-black.ttf'
  - id: 3
    type: '丸ゴシック体'
    key: 'rounded-x-mplus-1p-black'
    name: 'Rounded M+ 1p black'
    path: 'ja/rounded-x-mplus-1p-black.ttf'
  - id: 4
    type: '明朝体'
    key: 'ipamjm'
    name: 'IPAmj明朝'
    path: 'ja/ipamjm.ttf'
  - id: 5
    type: '毛筆'
    key: 'aoyagireisyoshimo'
    name: '青柳隷書しも'
    path: 'ja/aoyagireisyosimo_otf_2_01.otf'
  - id: 6
    type: '英字'
    key: 'LinLibertine_RBah'
    name: 'LinLibertine Bold'
    path: 'ja/LinLibertine_RBah.ttf'
  - id: 7
    type: 'JK丸ゴ'
    key: 'JKMaruGothic'
    name: 'JK Maru-Gothic M'
    path: 'ja/JK-Maru-Gothic-M.otf'
  - id: 8
    type: 'JK丸ゴ'
    key: 'Kirugo'
    name: 'GN-キルゴUかなNB'
    path: 'ja/GN-KillGothic-U-KanaNB.ttf'
  - id: 9
    type: 'memoir'
    key: 'memoir'
    name: 'めもわーる'
    path: 'ja/memoir.otf'
  - id: 10
    type: '851tiyayowaku'
    key: '851tiyayowaku'
    name: '851チカラヨワク'
    path: 'ja/851CHIKARA-YOWAKU_002.ttf'
  - id: 11
    type: '玉ねぎ楷書激無料版v7改'
    key: '玉ねぎ楷書激無料版v7改'
    name: '玉ねぎ楷書激無料版v7改'
    path: 'ja/玉ねぎ楷書激無料版v7改.ttf'
